Repository Jayshah6699/datascience-mashup, pull requests merged in 2021-02, with the labels that each got.

#231 Added HuggingFace's Transformer Tasks
  HuggingFace Transformer/README.md
  HuggingFace Transformer/Transformers.ipynb
Labels: DWOC, Level-4

#193 Loan Prediction
  Loan Prediction with deployment/Loanprediction.ipynb
  Loan Prediction with deployment/Procfile
  Loan Prediction with deployment/Readme.md
  Loan Prediction with deployment/app.py
  Loan Prediction with deployment/model.pkl
  Loan Prediction with deployment/requirements.txt
  Loan Prediction with deployment/templates/index.html
Labels: DWOC, Level-4

#234 covid19 case tracker
  covid-19 case tracker with GUI/README.md
  covid-19 case tracker with GUI/app.py
  covid-19 case tracker with GUI/images/corona19.jpg
  covid-19 case tracker with GUI/images/covid_1.jpg
  covid-19 case tracker with GUI/images/covid_2.jpg
  covid-19 case tracker with GUI/screen/test.py
Labels: DWOC, Level-3

#236 Flight Delay Prediction PR
  Flight Delay Prediction/Flight_Delay_Prediction.ipynb
  Flight Delay Prediction/readme.md
Labels: DWOC, Level-4

#237 Added Casava Plant Disease Classification
  Cassava Leaf Disease Classification/Cassava_Plant_Disease.ipynb
  Cassava Leaf Disease Classification/README.md
Labels: DWOC, Level-4

#241 Kickstart Projects Classification
  Kickstart Projects Classification/README.md
  Kickstart Projects Classification/kickass_project_classification.ipynb
Labels: DWOC, Level-4

#242 Voice-based gender identification
  Voice-Gender identification/Gender_Voice.ipynb
  Voice-Gender identification/Outputs/Models.png
  Voice-Gender identification/Outputs/dnn_model.PNG
  Voice-Gender identification/Outputs/genderVoice.png
  Voice-Gender identification/README.md
Labels: DWOC, Level-4

#247 Cryptocurrency Data Analysis and Visualization PR
  Cryptocurrency Data Analysis and Visualization/coinmarketcap_06122017.csv
  Cryptocurrency Data Analysis and Visualization/notebook1_bitcoin.ipynb
Labels: DWOC, Level-4

#246 added document matcher
  Document matcher/README.md
  Document matcher/dataset/document1.png
  Document matcher/dataset/document2.png
  Document matcher/match.py
  Document matcher/matcher_notebook.ipynb
  Document matcher/output/document1.png/1-header.jpg
  Document matcher/output/document1.png/2-header-dilated-eroded.jpg
  Document matcher/output/document1.png/3-header-canny.jpg
  Document matcher/output/document1.png/4-found-logo.jpg
  Document matcher/output/document1.png/5-header-pair.jpg
  Document matcher/output/document1.png/6-header-rectangle.jpg
  Document matcher/output/document1.png/7-matched-logo.jpg
Labels: DWOC, Level-4

#252 Added a Web App for Finger Sign Classification
  Finger Sign Classification WebApp/Procfile
  Finger Sign Classification WebApp/README.md
  Finger Sign Classification WebApp/ResNetModel.json
  Finger Sign Classification WebApp/ResNetModelWeights.h5
  Finger Sign Classification WebApp/app.py
  Finger Sign Classification WebApp/screenshot.png
  Finger Sign Classification WebApp/setup.sh
Labels: DWOC, Level-5

#251 Chicago Crime Rate
  Chicago Crime Rate/ChicagoCrimeRate.ipynb
  Chicago Crime Rate/ChicagoCrimeRate.pdf
  Chicago Crime Rate/Readme.md
Labels: DWOC, Level-4

#255 Added own facial recognition
  Build own facial detection/README.md
  Build own facial detection/face_rec.py
  Build own facial detection/faces/Bharath C S.jpg
  Build own facial detection/faces/bill gates.jpg
  Build own facial detection/faces/donald trump.jpg
  Build own facial detection/faces/elon musk.jpg
  Build own facial detection/faces/jeff bezos.jpg
  Build own facial detection/faces/obama.jpg
  Build own facial detection/output_face_rec.PNG
  Build own facial detection/own_facial_recogniton_notebook.ipynb
  Build own facial detection/requirements.txt
  Build own facial detection/test1.PNG
Labels: DWOC, Level-3

#261 Added Movie Reviews Text Analysis using NLTK
  Movie Reviews Analysis/MovieReviews.ipynb
  Movie Reviews Analysis/README.md
Labels: DWOC, Level-3

#268 Adding Logos
  assets/logos/analyze cryptocurrency data.png
  assets/logos/classify cassava leaf disease.png
  assets/logos/crime rate in chicago.png
  assets/logos/predict cuisine.png
  assets/logos/recognize digits.png
Labels: DWOC, Level-5

#272 Adding Logos
  assets/logos/classify finger signs.png
  assets/logos/classify project.png
  assets/logos/match document.png
  assets/logos/predict flight delay.png
  assets/logos/transformer.png
Labels: DWOC, Level-5

#270 Weather Analyser
  Weather_Analyser/Weather_Analyser.ipynb
  Weather_Analyser/Weather_Data.csv
Labels: DWOC, Level-3

#277 Color detection image
  color_detection_image/Color_Detection_Image.ipynb
  color_detection_image/README.md
  color_detection_image/color_detection.py
  color_detection_image/colorpic.jpg
  color_detection_image/colors.csv
  color_detection_image/lion.jfif
  color_detection_image/nature.jfif
  color_detection_image/output_gif.gif
  color_detection_image/pic1.jpg
  color_detection_image/pic2.jpg
  color_detection_image/pic3.jpg
Labels: DWOC, Level-4

#280 Adding Logos
  assets/logos/CLassify music.png
  assets/logos/detect face.png
  assets/logos/named entity recognition.png
  assets/logos/predict loan.png
  assets/logos/recommend movie.png
Labels: DWOC, Level-5

#281 Added Comparision of cosmetics by ingredients folder
  Cosmetics Comparison by ingredients/cosmetics.csv
  Cosmetics Comparison by ingredients/notebook.ipynb
  Cosmetics Comparison by ingredients/readme.md
Labels: DWOC, Level-4

#288 Added Fake News Detection using LSTM
  Fake News Detection using LSTM/Fake_News_detector_using_LSTM.ipynb
  Fake News Detection using LSTM/README.md
  Fake News Detection using LSTM/classification.png
Labels: DWOC, Level-3

#292 Reducing Traffic Mortality in USA pull request
  Traffic mortality in USA/miles-driven.csv
  Traffic mortality in USA/readme.md
  Traffic mortality in USA/road-accidents.csv
  Traffic mortality in USA/traffic_mortality.ipynb
Labels: DWOC, Level-4

#291 Qr scanner code added
  QR Detection/QR Detection .ipynb
  QR Detection/qrcodes.csv
  QR Detection/realtime_qrscanner.py
Labels: DWOC, Level-4

#296 Adding Logos
  assets/logos/generate text.png
  assets/logos/predict Parkinson's disease.png
  assets/logos/predict credit card approval.png
  assets/logos/predict score.png
  assets/logos/predict used car.png
Labels: DWOC, Level-5

#300 Adding Logos
  classify traffic signs.png
  detect face (1).png
  predict cosmetics.png
  predict flight price.png
  predict natural disaster.png
Labels: DWOC, Level-5

#299 Blood donor prediction
  Blood donors prediction/README.md
  Blood donors prediction/notebook.ipynb
  Blood donors prediction/transfusion.data
Labels: DWOC, Level-4

#303 Added Netflix EDA and Genre Prediction using Bert
  Netflix EDA and Genre Prediction/Netflix_Genre_Prediction.ipynb
  Netflix EDA and Genre Prediction/README.md
Labels: DWOC, Level-3

#307 Email Classification as spam or not
  email_classification/Email_Project.ipynb
  email_classification/Email_Project.py
  email_classification/README.md
  email_classification/requirements.txt
  email_classification/spam.csv
Labels: DWOC, Level-3

#308 ASL prediction webapp
  ASL prediction/ASL Recognition.ipynb
  ASL prediction/Procfile
  ASL prediction/README.md
  ASL prediction/abc_model.json
  ASL prediction/abc_model_weights.h5
  ASL prediction/acl_gif.gif
  ASL prediction/app.py
  ASL prediction/readme_image/initial_page'.PNG
  ASL prediction/readme_image/out_image.PNG
  ASL prediction/requirements.txt
  ASL prediction/setup.sh
Labels: DWOC, Level-4

#317 Logos
  assets/logos/Traffic Mortality.png
  assets/logos/detect QR.png
  assets/logos/detect color.png
  assets/logos/predict video game sales.png
  assets/logos/voice-based gender identification.png
Labels: DWOC, Level-5

#319 Added Alexa Reviews Analysis
  Alexa Reviews Analysis/Alexa_Reviews.ipynb
  Alexa Reviews Analysis/README.md
Labels: DWOC, Level-3

#329 Adding Logos
  assets/logos/detect fake  news using lstm.png
  assets/logos/find  blood donor.png
  assets/logos/predict  covid-19.png
  assets/logos/predict  genre.png
  assets/logos/predict brain tumor.png
Labels: DWOC, Level-5

#330 Heart disease prediction using 7 ML algorithms
  heart disease prediction/Heart_disease_prediction.ipynb
  heart disease prediction/README.md
  heart disease prediction/heart.csv
Labels: DWOC, Level-5

#332 Handwritten letter and digit prediction
  Handwritten letter and digit prediction/Handwritten_Letter.ipynb
  Handwritten letter and digit prediction/Readme.md
Labels: DWOC, Level-4

#333 Adding project Logos
  assets/logos/Analyze market basket.png
  assets/logos/classify email.png
  assets/logos/detect gender using name.png
  assets/logos/predict asl.png
  assets/logos/predict malaria.png
Labels: DWOC, Level-5

#336 Voice Emotion Recognition
  Voice emotion recognition/Readme.md
  Voice emotion recognition/Voice_Sentiment_Recognition.ipynb
Labels: DWOC, Level-4

#338 Sentimental-Analysis
  Sentimental-Analysis/README.md
  Sentimental-Analysis/Sentimental.ipynb
  Sentimental-Analysis/emotions.txt
  Sentimental-Analysis/read.txt
  Sentimental-Analysis/sentimentGraph.png
  Sentimental-Analysis/sentimental.py
Labels: DWOC, Level-3

#339 Updated Project Interface
  Project Interface/index.html
  Project Interface/onlycss.css
  Project Interface/onlyhtml.html
Labels: DWOC, Level-5

#342 Added CAPTCHA Recognition
  CAPTCHA Recognition/Captcha Recognition.ipynb
  CAPTCHA Recognition/README.md
  CAPTCHA Recognition/output.png
Labels: DWOC, Level-4

#346 Adding designs
  assets/logos/analyze stock sentiments.png
  assets/logos/confusion matrix.png
  assets/logos/image segmentation.png
  assets/logos/lstm.png
  assets/logos/recognize alphabets.png
  assets/logos/summarize text.png
Labels: DWOC, Level-5

#347 Beta Calculation, CAPM and gold price prediction PR
  CAPM and Beta using Sklearn/GOLD.csv
  CAPM and Beta using Sklearn/Nifty50.csv
  CAPM and Beta using Sklearn/hul2.csv
  CAPM and Beta using Sklearn/notebook3.ipynb
  CAPM and Beta using Sklearn/readme.md
Labels: DWOC, Level-3

#349 Adding designs
  assets/logos/analyze Alexa product review.png
  assets/logos/analyze weather.png
  assets/logos/forecast weather.png
  assets/logos/predict wine quality.png
  assets/logos/recognise emotion.png
Labels: DWOC, Level-5

#353 Cluster analysis of stocks PR
  Cluster Analysis of Stocks/Large_Cap.zip
  Cluster Analysis of Stocks/Mid_Cap.zip
  Cluster Analysis of Stocks/Small_Cap.zip
  Cluster Analysis of Stocks/notebook6.ipynb
  Cluster Analysis of Stocks/readme.md
Labels: DWOC, Level-4

#354 Uber data analysis
  Uber Data Analysis/Readme.md
  Uber Data Analysis/Uber_data_Visualization.ipynb
Labels: DWOC, Level-4

#360 Updated Interface
  Project Interface/index.html
  Project Interface/onlyhtml.html
Labels: DWOC, Level-5

#361 football best 11
  Football Dataset/Football_analysis.ipynb
  Football Dataset/FullData.csv
Labels: DWOC, Level-3

#363 Passenger traffic
  PassengerTraffic in Airplane/AirPassengers.csv
  PassengerTraffic in Airplane/Passenger traffic.ipynb
Labels: DWOC, Level-3

#364 Adding Designs
  assets/logos/analyze police dataset (2).png
  assets/logos/cluster analysis of stocks.png
  assets/logos/predict IPL performance.png
  assets/logos/recognize captcha.png
  assets/logos/visualize  uber data.png
Labels: DWOC, Level-5

#367 Google_playstore
  GooglePlaystorerating/Google_playstore rating.ipynb
  GooglePlaystorerating/googleplaystore.csv
Labels: DWOC, Level-3
