Repository Jayshah6699/datascience-mashup, pull requests merged in 2021-01, with the labels that each got.

#30 Dataset clean
  dataset-refine/dataClean.py
  dataset-refine/dataset-files/chennai_house_price_prediction.csv
  dataset-refine/dataset-files/churn_prediction.csv
  dataset-refine/dataset-files/train.csv
  dataset-refine/dataset-files/train_bm.csv
  dataset-refine/readme.md
  dataset-refine/updated-files/chennai_house_price_prediction-cleaned.csv
  dataset-refine/updated-files/churn_prediction-cleaned.csv
  dataset-refine/updated-files/train-cleaned.csv
  dataset-refine/updated-files/train_bm-cleaned.csv
Labels: DWOC, Level-5

#29 Added all the files related to predicting employee attrition project
  Bank Loan prediction/Machine Learning.ipynb
  Bank Loan prediction/Visualizations.ipynb
  Bank Loan prediction/test_Y3wMUE5_7gLdaTN.csv
  Bank Loan prediction/train_u6lujuX_CVtuZ9i.csv
  Predicting Employee Attrition/1
  Predicting Employee Attrition/data description.txt
  Predicting Employee Attrition/hr-attrition-prediction.ipynb
  Predicting Employee Attrition/testing_data.csv
  Predicting Employee Attrition/training_data.csv
Labels: DWOC, Level-5

#33 Revert "Added all the files related to predicting employee attrition project"
  Bank Loan prediction/Machine Learning.ipynb
  Bank Loan prediction/Visualizations.ipynb
  Bank Loan prediction/test_Y3wMUE5_7gLdaTN.csv
  Bank Loan prediction/train_u6lujuX_CVtuZ9i.csv
  Predicting Employee Attrition/1
  Predicting Employee Attrition/data description.txt
  Predicting Employee Attrition/hr-attrition-prediction.ipynb
  Predicting Employee Attrition/testing_data.csv
  Predicting Employee Attrition/training_data.csv
Labels: DWOC, Level-5

#31 predicting compressive strength of concrete
  concrete strength prediction/README.md
  concrete strength prediction/concrete-strength-using-a-deep-neural-network.ipynb
Labels: DWOC, Level-5, documentation

#37 Created CONTRIBUTING.md
  CONTRIBUTING.md
Labels: DWOC, Level-2, Level-3

#41 README.md for breast cancer prediction
  BreastCancerPrediction/README.md
  BreastCancerPrediction/snapshot.png
Labels: DWOC, Level-1, Level-2

#45 Titanic Survivals Predictions
  titanic-survivals/titanic-survival.ipynb
Labels: DWOC, Level-4

#59 Updated Readme.md of Handwritten Digits Recognition Project
  Handwritten Digits Recognition/README.md
Labels: DWOC, Level-2, documentation

#63 Text Classification using Naive Bayes
  Text Classification using Naive Bayes/NaiveBayesAssignment.ipynb
  Text Classification using Naive Bayes/README.md
Labels: DWOC, Level-5

#65 Graphs for visualisation for issue #17
  Graphs for Visualisation/Graphs in Seaborn(Data Visualisation).ipynb
  Graphs for Visualisation/Loan Prediction Dataset.csv
  Graphs for Visualisation/Readme.md
Labels: DWOC, Level-2, Level-4

#66 #12 Data Science Project "Coronary Heart Disease Prediction Web App"
  Coronary Heart Disease Prediction/Dataset/framingham.csv
  Coronary Heart Disease Prediction/Procfile
  Coronary Heart Disease Prediction/README.md
  Coronary Heart Disease Prediction/app.py
  Coronary Heart Disease Prediction/css/styles.css
  Coronary Heart Disease Prediction/model.py
  Coronary Heart Disease Prediction/requirements.txt
  Coronary Heart Disease Prediction/setup.sh
  Coronary Heart Disease Prediction/utils.py
Labels: DWOC, Level-5, documentation

#71 Shakespeare style text generation
  Shakespeare style text generation/README.md
  Shakespeare style text generation/Shakespeare.ipynb
Labels: DWOC, Level-5

#73 Stock Price Prediction
  Stock Price Prediction/Data Collection.ipynb
  Stock Price Prediction/Model_Notebook.ipynb
  Stock Price Prediction/google_dataset.csv
  Stock Price Prediction/model.h5
Labels: DWOC, Level-4

#76 Contributors Table Update in README.md
  README.md
Labels: DWOC, Level-2

#77 Issue number #43
  RestaurantReview/ReadMe.md
  RestaurantReview/RestaurantReview.ipynb
  RestaurantReview/Restaurant_Reviews.tsv
Labels: DWOC, Level-4

#69 Added "Dogs vs Cats" Project
  Dogs vs Cats/Dogs_vs_Cats .ipynb
  Dogs vs Cats/README.md
Labels: DWOC, Level-4

#82 Issue #78
  Mall Customers Segmentation using clustering/Mall_Customers.csv
  Mall Customers Segmentation using clustering/README.md
  Mall Customers Segmentation using clustering/TypesOfCustomer.ipynb
Labels: DWOC, Level-5

#90 car price prediction model
  car_price_pred_ai/Procfile
  car_price_pred_ai/app.py
  car_price_pred_ai/car_data.csv
  car_price_pred_ai/car_price_prediction.ipynb
  car_price_pred_ai/car_price_prediction.py
  car_price_pred_ai/project_live_link.txt
  car_price_pred_ai/random_forest_regression_model.pkl
  car_price_pred_ai/requirements.txt
  car_price_pred_ai/static/css/abcd1.jpg
  car_price_pred_ai/templates/index.html
Labels: DWOC, Level-5

#97 Added readme, csv file and code for apple stock prediction
  Apple Stock Price Detection/AAPL 2019-2020 data.csv
  Apple Stock Price Detection/EOD-AAPL.csv
  Apple Stock Price Detection/aapl_2019-2020_analysed.ipynb
  Apple Stock Price Detection/readme.md
  Apple Stock Price Detection/stocks_aapl.ipynb
Labels: DWOC, Level-5

#122 Added Traffic Signs Recognition Project
  Traffic Signs Recognition/README.md
  Traffic Signs Recognition/Traffic_Signs_Recognition.ipynb
Labels: DWOC, Level-4

#117 Weather prediction #96
  weather/CleanData.csv
  weather/Data Formation.ipynb
  weather/Neural model of Weather Prediction.ipynb
  weather/README.md
Labels: DWOC, Level-4

#120 Earthquake Prediction
  Earthquake Prediction/FeatureExtraction.ipynb
  Earthquake Prediction/Modeling.ipynb
  Earthquake Prediction/README.md
  Earthquake Prediction/SampleEDA.ipynb
  Earthquake Prediction/TestData.ipynb
Labels: DWOC, Level-5

#128 Project Logos
  assets/logos/Dog VS Cat.png
  assets/logos/Heart Disease Prediction.png
  assets/logos/Predict Breast Cancer.png
  assets/logos/Shakespeare Text.png
  assets/logos/Stock Prediction.png
Labels: DWOC, Level-5

#132 Logos II
  assets/logos/Analyse Sentiment.png
  assets/logos/Predict House Price.png
  assets/logos/Recognise Digits.png
  assets/logos/Text Classifier.png
  assets/logos/face detector and age-gender classifier.png
Labels: DWOC, Level-5

#136 Final LOGOS
  assets/logos/Salary predictor.png
  assets/logos/Visualization mashup.png
  assets/logos/_dataset refiner.png
  assets/logos/_restaurant review classifier.png
  assets/logos/predict concrete strength.png
Labels: DWOC, Level-5

#140 [Added] added IrisFlowerDT
  IrisFlower(DT)/IrisFlower_DT.ipynb
Labels: DWOC, Level-4

#111 TMDb Movie Analysis and Prediction
  Coronary Heart Disease Prediction/css/styles.css
  TMDb Movie Analysis and Prediction/README.md
  TMDb Movie Analysis and Prediction/TMDb_Movie_Analysis_and_Comparative_Prediction_.ipynb
Labels: DWOC, Level-4

#142 Wordcloud
  Different visualisations/wordcloud/(1) The Hunger Games.txt
  Different visualisations/wordcloud/moustache.jpg
  Different visualisations/wordcloud/moustache_out.png
  Different visualisations/wordcloud/readme.md
  Different visualisations/wordcloud/wordcloud.py
Labels: DWOC, Level-1, Level-4

#144 Amazon Reviews Sentiment Analyzer
  Amazon Reviews Sentiment Analysis using Linear Classifiers/README.md
  Amazon Reviews Sentiment Analysis using Linear Classifiers/dataset/200.txt
  Amazon Reviews Sentiment Analysis using Linear Classifiers/dataset/4000.txt
  Amazon Reviews Sentiment Analysis using Linear Classifiers/dataset/reviews_submit.tsv
  Amazon Reviews Sentiment Analysis using Linear Classifiers/dataset/reviews_test.tsv
  Amazon Reviews Sentiment Analysis using Linear Classifiers/dataset/reviews_train.tsv
  Amazon Reviews Sentiment Analysis using Linear Classifiers/dataset/reviews_val.tsv
  Amazon Reviews Sentiment Analysis using Linear Classifiers/dataset/stopwords.txt
  Amazon Reviews Sentiment Analysis using Linear Classifiers/dataset/toy_data.tsv
  Amazon Reviews Sentiment Analysis using Linear Classifiers/main.ipynb
  Amazon Reviews Sentiment Analysis using Linear Classifiers/main.py
  Amazon Reviews Sentiment Analysis using Linear Classifiers/project1.py
  Amazon Reviews Sentiment Analysis using Linear Classifiers/test.py
  Amazon Reviews Sentiment Analysis using Linear Classifiers/utils.py
Labels: DWOC, Level-4

#148 Integrate Welcome and Greeting Bot
  .github/config.yml
Labels: DWOC, Level-1, documentation

#147 DCGAN on Fashion MNIST
  Fashion MNIST GAN/DCGAN_fashionMNIST.ipynb
  Fashion MNIST GAN/Outputs/actual.png
  Fashion MNIST GAN/Outputs/dcgan_mnist.gif
  Fashion MNIST GAN/Outputs/disc_plot.png
  Fashion MNIST GAN/Outputs/gan.png
  Fashion MNIST GAN/Outputs/gen_plot.png
  Fashion MNIST GAN/Outputs/generated.png
  Fashion MNIST GAN/Outputs/model.png
  Fashion MNIST GAN/README.md
Labels: DWOC, Level-4

#156 UrbanSound8k
  UrbanSound8K/README.md
  UrbanSound8K/UrbanSound8K.ipynb
  UrbanSound8K/best_model.hdf5
Labels: DWOC, Level-5

#157 Heart Disease - Classifications (Machine Learning) #139
  Predicting-Heart-Disease-master/Heart Disease Predictions.ipynb
  Predicting-Heart-Disease-master/dataset.csv
Labels: DWOC, Level-4

#158 Updated README.md of Dogs vs Cats Project
  Dogs vs Cats/README.md
Labels: DWOC, Level-1

#161 PROJECT INTERFACE
  Project Interface/ProjectInterface.html
  Project Interface/onlycss.css
  Project Interface/onlyhtml.html
Labels: DWOC, Level-5

#164 Adding Logos
  assets/logos/DETECT FAKE NEWS.png
  assets/logos/PREDICT CAR PRICE.png
  assets/logos/PREDICT RAINFALL.png
  assets/logos/RECOGNIZE TRAFFIC SIGNS.png
  assets/logos/predict  EARTHQUAKE.png
Labels: DWOC, Level-5

#167 Credit Card Fraud Detection
  Credit Card Fraud Detection/README.md
  Credit Card Fraud Detection/credit-card-fraud-detection.ipynb
Labels: DWOC, Level-4

#169 Updated Readme.md of Traffic Signs Recognition Project
  Traffic Signs Recognition/README.md
Labels: DWOC, Level-1

#172 Butterfly Classification
  .DS_Store
  Butterfly Classification/ButterflyClassification.ipynb
  Butterfly Classification/README.md
  ButterflyClassification.ipynb
  butterfly_classification.ipynb
Labels: DWOC, Level-4

#170 diabities prediction #159
  Diabetes-Prediction-master/Diabetes_Prediction.ipynb
  Diabetes-Prediction-master/data/pima-data.csv
Labels: DWOC, Level-4

#177 Adding Logos
  assets/logos/analyze movie.png
  assets/logos/classify sound.png
  assets/logos/detect credit card fraud.png
  assets/logos/predict employee turnover (1).png
  assets/logos/predict weather.png
Labels: DWOC, Level-5

#186 README.md
  House_Price_Prediction/Img003.jpg
  House_Price_Prediction/Img004.jpg
  House_Price_Prediction/README.md
Labels: DWOC, Level-1

#187 Bitcoin Price Prediciton
  Bitcoin_Prediction/Bitcoin_prediction.png
  Bitcoin_Prediction/README.md
  Bitcoin_Prediction/bitcoin-prediction.ipynb
Labels: DWOC, Level-4

#192 Adding Logos
  assets/logos/analyze product review.png
  assets/logos/classify butterflies.png
  assets/logos/cluster customers.png
  assets/logos/predict heart disease.png
  assets/logos/predict survival.png
Labels: DWOC, Level-5

#204 Adding Logos
  detect apple stock price.png
  predict bitcoin.png
  predict cloth fabric.png
  predict diabetes.png
  predict flight fare.png
Labels: DWOC, Level-5

#146 Added Natural Disaster Prediction
  Natural Disaster Prediction/README.md
  Natural Disaster Prediction/natural_disaster.ipynb
Labels: DWOC, Level-4

#199 Text_generator project #198
  Text Generator/frankenstein.txt
  Text Generator/text_generation_project.ipynb
Labels: DWOC, Level-3

#201 Used car price estimation: 96% accuracy #175
  Used_car_prediction/car_predict.ipynb
  Used_car_prediction/submission.csv
  Used_car_prediction/test-data.csv
  Used_car_prediction/train-data.csv
Labels: DWOC, Level-4

#216 Wine Quality
  Wine Quality/README.md
  Wine Quality/Wine_Quality.ipynb
Labels: DWOC, Level-3

#153 Credit Card Approval Prediction
  Predicting Credit Card Approvals/Credit_datascience.ipynb
  Predicting Credit Card Approvals/datasets/cc_approvals.data
  Predicting Credit Card Approvals/readme.md
Labels: DWOC, Level-4

#228 Video Games Sales Prediction
  Video Game Sales Prediciton/Global-Sales.png
  Video Game Sales Prediciton/README.md
  Video Game Sales Prediciton/sales-per-genre(global).png
  Video Game Sales Prediciton/videogamespredicition.ipynb
  Video Game Sales Prediciton/year-wise-sales.png
Labels: DWOC, Level-3

#227 README.md for "Car-Price-Prediction-AI" #191
  car_price_pred_ai/README.md
  car_price_pred_ai/car_price_i.jpg
Labels: DWOC, Level-1

#224 Added Perkinson's Prediction
  Perkinson's Disease Prediction/Perkinsons_Prediction.ipynb
  Perkinson's Disease Prediction/README.md
Labels: DWOC, Level-4

#226 Digit Recognition #85
  Digit_Recognition/Digit_Recognition.ipynb
Labels: DWOC, Level-1
